/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lungwil' at '11/6/16 8:32 PM' with Gradle 3.1
 *
 * @author lungwil, @date 11/6/16 8:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
